name: BedWars1058
api-version: '1.13'
version: v1.0
authors: [JektDV, Necro]
description: Bed Wars Minigame by Andrei1058, forked by JektDV & Necro
main: com.andrei1058.bedwars.BedWars
softdepend: [Vault,PlaceholderAPI,Citizens,Parties,SlimeWorldManager,VipFeatures,Enhanced-SlimeWorldManager,PartyAndFriends,Spigot-Party-API-PAF]
load: STARTUP
